[phases.setup]
nixPkgs = ['jdk17_headless', 'maven']

[phases.build]
cmds = ['./mvnw clean package -DskipTests']
dependsOn = ['setup']
cacheDirectories = []

[start]
cmd = 'java -jar target/swachh-drishti-0.0.1-SNAPSHOT.jar'